@startuml
' 文档网址：https://plantuml.com/zh/
' 编辑网址：http://www.plantuml.com/plantuml/uml

map ACT_CMMN_CASEDEF {
  ID_ => 主键
  REV_ =>
  NAME_ => 名称
  KEY_ =>
  VERSION_ =>
  CATEGORY_ =>
  DEPLOYMENT_ID_ => 关联ACT_CMMN_DEPLOYMENT表ID
  RESOURCE_NAME_ =>
  DESCRIPTION_ =>
  HAS_GRAPHICAL_NOTATION_ =>
  TENANT_ID_ =>
  DGRM_RESOURCE_NAME_ =>
  HAS_START_FORM_KEY_ =>
}

map ACT_CMMN_DATABASECHANGELOG {
  ID => 主键
  AUTHOR => 操作人
  FILENAME => 文件名
  DATEEXECUTED => 执行时间
  ORDEREXECUTED => 执行顺序
  EXECTYPE =>
  MD5SUM =>
  DESCRIPTION => 描述
  COMMENTS =>
  TAG => 标签
  LIQUIBASE =>
  CONTEXTS =>
  LABELS =>
  DEPLOYMENT_ID =>
}

map ACT_CMMN_DATABASECHANGELOGLOCK {
  ID => 主键
  LOCKED =>
  LOCKGRANTED => 锁定时间
  LOCKEDBY => 锁定者
}

map ACT_CMMN_DEPLOYMENT {
  ID_ => 主键
  NAME_ => 名称
  CATEGORY_ => 类别
  KEY_ =>
  DEPLOY_TIME_ => 布署时间
  PARENT_DEPLOYMENT_ID_ =>
  TENANT_ID_ =>
}

map ACT_CMMN_DEPLOYMENT_RESOURCE {
  ID_ => 主键
  NAME_ => 名称
  DEPLOYMENT_ID_ => 关联ACT_DMN_DEPLOYMENT表ID
  RESOURCE_BYTES_ => 源码
  GENERATED_ =>
}

map ACT_CMMN_HI_CASE_INST {
  ID_ => 主键
  REV_ => 
  BUSINESS_KEY_ => 
  NAME_ => 名称
  PARENT_ID_ =>
  CASE_DEF_ID_ => 
  STATE_ => 状态
  START_TIME_ => 开始时间 
  END_TIME_ => 结束时间
  START_USER_ID_ =>  开始用户ID
  CALLBACK_ID_ => 回调ID
  CALLBACK_TYPE_ => 回调类别
  TENANT_ID_ =>
}

map ACT_CMMN_HI_MIL_INST {
  ID_ => 主键
  REV_ => 
  NAME_ => 名称
  TIME_STAMP_ =>  时间戳
  CASE_INST_ID_ => 
  CASE_DEF_ID_ =>
  ELEMENT_ID_ =>
}

map ACT_CMMN_RU_CASE_INST {
  ID_ => 主键
  REV_ => 
  BUSINESS_KEY_ => 
  NAME_ => 名称
  PARENT_ID_ => 
  CASE_DEF_ID_ => 
  STATE_ => 状态
  START_TIME_ => 开始时间 
  START_USER_ID_ => 开始用户ID
  CALLBACK_ID_ => 回调ID
  CALLBACK_TYPE_ => 回调类型
  TENANT_ID_ => 
  LOCK_TIME_ => 
  IS_COMPLETEABLE_ => 
}

map ACT_CMMN_RU_MIL_INST {
  ID_ => 主键
  NAME_ => 名称
  TIME_STAMP_ => 时间戳
  CASE_INST_ID_ => 
  CASE_DEF_ID_ => 
  ELEMENT_ID_ => 
}

map ACT_CMMN_RU_PLAN_ITEM_INST{
  ID_ => 主键
  REV_ => 
  CASE_DEF_ID_ => 关联ACT_CMMN_CASEDEF表ID
  CASE_INST_ID_ => 关联ACT_CMMN_RU_CASE_INST表ID
  STAGE_INST_ID_ =>
  IS_STAGE_ => 
  ELEMENT_ID_ => 
  NAME_ => 名称
  STATE_ => 状态
  START_TIME_ => 开始时间
  START_USER_ID_ => 开始用户ID
  REFERENCE_ID_ =>
  REFERENCE_TYPE_ => 
  TENANT_ID_ => 
  ITEM_DEFINITION_ID_ =>
  ITEM_DEFINITION_TYPE_ =>
  IS_COMPLETEABLE_ =>
  IS_COUNT_ENABLED_ =>
  VAR_COUNT_ =>
  SENTRY_PART_INST_COUNT_ =>
}

map ACT_CMMN_RU_SENTRY_PART_INST {
  ID_ => 主键
  REV_ =>
  CASE_DEF_ID_ => 关联ACT_CMMN_CASEDEF表ID
  CASE_INST_ID_ => 关联ACT_CMMN_RU_CASE_INST表ID
  PLAN_ITEM_INST_ID_ => 关联ACT_CMMN_RU_PLAN_ITEM_INST表ID
  ON_PART_ID_ =>
  IF_PART_ID_ => 
  TIME_STAMP_ => 时间戳  
}
ACT_FK_CASE_DEF_DPLY::DEPLOYMENT_ID_ --> ACT_CMMN_DEPLOYMENT::ID_
ACT_FK_CMMN_RSRC_DPL::DEPLOYMENT_ID_ --> ACT_CMMN_DEPLOYMENT::ID_

ACT_FK_CASE_INST_CASE_DEF::CASE_DEF_ID_ --> ACT_CMMN_CASEDEF::ID_

ACT_FK_MIL_CASE_DEF::CASE_DEF_ID_ --> ACT_CMMN_CASEDEF::ID_
ACT_FK_MIL_CASE_INST::CASE_INST_ID_ --> ACT_CMMN_RU_CASE_INST::ID_

ACT_FK_PLAN_ITEM_CASE_DEF::CASE_DEF_ID_ --> ACT_CMMN_CASEDEF::ID_
ACT_FK_PLAN_ITEM_CASE_INST::CASE_INST_ID_ --> ACT_CMMN_RU_CASE_INST::ID_

ACT_CMMN_CASEDEF::DEPLOYMENT_ID_ --> ACT_CMMN_DEPLOYMENT::ID_
ACT_CMMN_DEPLOYMENT_RESOURCE::DEPLOYMENT_ID_ --> ACT_CMMN_DEPLOYMENT::ID_
ACT_CMMN_RU_SENTRY_PART_INST::CASE_DEF_ID_ --> ACT_CMMN_CASEDEF::ID_

ACT_CMMN_RU_PLAN_ITEM_INST::CASE_DEF_ID_ --> ACT_CMMN_CASEDEF::ID_
ACT_CMMN_RU_PLAN_ITEM_INST::CASE_INST_ID_ --> ACT_CMMN_RU_CASE_INST::ID_

ACT_CMMN_RU_SENTRY_PART_INST::CASE_INST_ID_ --> ACT_CMMN_RU_CASE_INST::ID_
ACT_CMMN_RU_SENTRY_PART_INST::PLAN_ITEM_INST_ID_ --> ACT_CMMN_RU_PLAN_ITEM_INST::ID_

ACT_FK_SENTRY_CASE_DEF::CASE_DEF_ID_ --> ACT_CMMN_CASEDEF::ID_
ACT_FK_SENTRY_CASE_INST::CASE_INST_ID_ --> ACT_CMMN_RU_CASE_INST::ID_
ACT_FK_SENTRY_PLAN_ITEM::PLAN_ITEM_INST_ID_ --> ACT_CMMN_RU_PLAN_ITEM_INST::ID_


map ACT_CO_CONTENT_ITEM {
  ID_ => 主键
  NAME_ => 名称
  MIME_TYPE_ => 类型
  TASK_ID_ => 
  PROC_INST_ID_ => 
  CONTENT_STORE_ID_ => 
  CONTENT_STORE_NAME_ => 
  FIELD_ => 
  CONTENT_AVAILABLE_ => 
  CREATED_ => 
  CREATED_BY_ => 
  LAST_MODIFIED_ => 
  LAST_MODIFIED_BY_ => 
  CONTENT_SIZE_ => 
  TENANT_ID_ => 
  SCOPE_ID_ => 
  SCOPE_TYPE_ => 
}

map ACT_CO_DATABASECHANGELOG {
  ID => 主键
  AUTHOR => 操作人
  FILENAME => 文件名
  DATEEXECUTED => 执行时间
  ORDEREXECUTED => 执行顺序
  EXECTYPE => 
  MD5SUM => 
  DESCRIPTION => 描述
  COMMENTS => 
  TAG => 标签
  LIQUIBASE =>
  CONTEXTS => 
  LABELS => 标签
  DEPLOYMENT_ID => 
}

map ACT_CO_DATABASECHANGELOGLOCK {
  ID => 主键    
  LOCKED => 
  LOCKGRANTED => 锁定时间 
  LOCKEDBY => 锁定者
}
@enduml
